version: "3.8"

services:
  primary:
    container_name: postgres-primary
    build:
      context: .
      args:
        PATH_TO_SCRIPTS: ./source
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: BgqzYc4lM7OypUh
      PGDATA: /data/
      POSTGRES_DB: postgresdb
      REPLICATION_USER: replicationuser
      REPLICATION_USER_PASSWORD: BgqzYc4lM7OypUh
      PRIMARY_HOSTNAME: postgres-primary
    volumes:
      - postgres_primary_volume:/data
      - ./source/config:/config
      - ./source/archive:/archive
    ports:
      - "5433:5432"
    networks:
      - sharding-network
    restart: unless-stopped
    command: postgres -c config_file=/config/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  standby-1:
    container_name: postgres-standby-1
    build:
      context: .
      args:
        PATH_TO_SCRIPTS: ./standby
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: BgqzYc4lM7OypUh
      PGDATA: /data/
      POSTGRES_DB: postgresdb
      REPLICATION_USER: replicationuser
      PRIMARY_HOSTNAME: postgres-primary
      CUSTOMER_PARTITIONS: |
        [
          {
            "NAME": "customers_child",
            "AGE_MIN": 0,
            "AGE_MAX": 12
          },
          {
            "NAME": "customers_teenager",
            "AGE_MIN": 12,
            "AGE_MAX": 18
          },
        ]
    volumes:
      - ./standby/config:/config
      - ./standby/archive:/mnt/server/archive
    ports:
      - "5434:5432"
    networks:
      - sharding-network
    restart: unless-stopped
    command: postgres -c config_file=/config/postgresql.conf
    depends_on:
      - primary
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  standby-2:
    container_name: postgres-standby-2
    build:
      context: .
      args:
        PATH_TO_SCRIPTS: ./standby
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: BgqzYc4lM7OypUh
      PGDATA: /data/
      POSTGRES_DB: postgresdb
      REPLICATION_USER: replicationuser
      PRIMARY_HOSTNAME: postgres-primary
      CUSTOMER_PARTITIONS: |
        [
          {
            "NAME": "customers_youngadult",
            "AGE_MIN": 18,
            "AGE_MAX": 30
          }
        ]
    volumes:
      - ./standby/config:/config
      - ./standby/archive:/mnt/server/archive
    ports:
      - "5435:5432"
    networks:
      - sharding-network
    restart: unless-stopped
    command: postgres -c config_file=/config/postgresql.conf
    depends_on:
      - primary
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  standby-3:
    container_name: postgres-standby-3
    build:
      context: .
      args:
        PATH_TO_SCRIPTS: ./standby
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: BgqzYc4lM7OypUh
      PGDATA: /data/
      POSTGRES_DB: postgresdb
      REPLICATION_USER: replicationuser
      PRIMARY_HOSTNAME: postgres-primary
      CUSTOMER_PARTITIONS: |
        [
          {
            "NAME": "customers_adult",
            "AGE_MIN": 30,
            "AGE_MAX": 55
          }
        ]
    volumes:
      - ./standby/config:/config
      - ./standby/archive:/mnt/server/archive
    ports:
      - "5436:5432"
    networks:
      - sharding-network
    restart: unless-stopped
    command: postgres -c config_file=/config/postgresql.conf
    depends_on:
      - primary
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  standby-4:
    container_name: postgres-standby-4
    build:
      context: .
      args:
        PATH_TO_SCRIPTS: ./standby
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: BgqzYc4lM7OypUh
      PGDATA: /data/
      POSTGRES_DB: postgresdb
      REPLICATION_USER: replicationuser
      PRIMARY_HOSTNAME: postgres-primary
      CUSTOMER_PARTITIONS: |
        [
          {
            "NAME": "customers_elder",
            "AGE_MIN": 55,
            "AGE_MAX": 200
          }
        ]
    volumes:
      - ./standby/config:/config
      - ./standby/archive:/mnt/server/archive
    ports:
      - "5437:5432"
    networks:
      - sharding-network
    restart: unless-stopped
    command: postgres -c config_file=/config/postgresql.conf
    depends_on:
      - primary
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  sharding-network:

volumes:
  postgres_primary_volume:
    external: true
