#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB"  <<-EOSQL
    CREATE USER $REPLICATION_USER WITH REPLICATION PASSWORD '$REPLICATION_USER_PASSWORD' LOGIN CONNECTION LIMIT 15;

    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $REPLICATION_USER;

    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $REPLICATION_USER;

    CREATE TABLE sensor_data (
        id BIGINT GENERATED ALWAYS AS IDENTITY,
        sensor_id INTEGER NOT NULL,
        timestamp TIMESTAMP NOT NULL,
        value NUMERIC NOT NULL
    )
    PARTITION BY HASH (sensor_id);

    CREATE TABLE sensor_data_1 PARTITION OF sensor_data
        FOR VALUES WITH (MODULUS 4, REMAINDER 0);

    CREATE TABLE sensor_data_2 PARTITION OF sensor_data
        FOR VALUES WITH (MODULUS 4, REMAINDER 1);

    CREATE TABLE sensor_data_3 PARTITION OF sensor_data
        FOR VALUES WITH (MODULUS 4, REMAINDER 2);

    CREATE TABLE sensor_data_4 PARTITION OF sensor_data
        FOR VALUES WITH (MODULUS 4, REMAINDER 3);

EOSQL