#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB"  <<-EOSQL
    CREATE USER $REPLICATION_USER WITH REPLICATION PASSWORD '$REPLICATION_USER_PASSWORD' LOGIN CONNECTION LIMIT 15;

    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $REPLICATION_USER;

    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $REPLICATION_USER;

    CREATE TABLE sales (
        id SERIAL PRIMARY KEY,
        product_id INTEGER,
        sales_date DATE,
        amount DECIMAL
    );

    CREATE SUBSCRIPTION sales_subscription
        CONNECTION 'dbname=$POSTGRES_DB host=$PRIMARY_HOSTNAME user=$REPLICATION_USER password=$REPLICATION_USER_PASSWORD'
        PUBLICATION sales_publication
        WITH (copy_data = false);
EOSQL